/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Control.DataComentarios;
import Control.DataEquipo;
import Control.DataEquipoMiembros;
import Control.DataMiembro;
import Control.DataProyecto;
import Control.DataTarea;
import Modelo.Comentarios;
import Modelo.Equipo;
import Modelo.EquipoMiembros;
import Modelo.Miembro;
import Modelo.Proyecto;
import Modelo.Tarea;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Valentin
 */
public class ConsultarProyectosView extends javax.swing.JInternalFrame {

    DataEquipo dataequipo = new DataEquipo();
    Equipo equipo = null;
    DataMiembro datamiembro = new DataMiembro();
    Miembro miembro = null;
    DataProyecto dataproyecto = new DataProyecto();
    Proyecto proyecto = null;
    DataTarea datatarea = new DataTarea();
    Tarea tarea = null;
    DataEquipoMiembros dataequipomiembros = new DataEquipoMiembros();
    EquipoMiembros equipomiembros = null;
    DataComentarios datacomentario = new DataComentarios();
    Comentarios comentarios = null;
    private DefaultTableModel tabla = new DefaultTableModel();

    public ConsultarProyectosView() {
        initComponents();
        cargarProyecto();
        tabla.setColumnCount(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jcbProyecto = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtTabla = new javax.swing.JTable();
        jcbEquipoMiembros = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jbMostrar = new javax.swing.JButton();
        jrbCompletada = new javax.swing.JRadioButton();
        jrbPendiente = new javax.swing.JRadioButton();
        jrbProgreso = new javax.swing.JRadioButton();
        jbSalir = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jbMostrarProyectos = new javax.swing.JButton();

        setTitle("Consultar Proyectos");
        setMaximumSize(new java.awt.Dimension(1000, 600));
        setMinimumSize(new java.awt.Dimension(1000, 600));
        setPreferredSize(new java.awt.Dimension(1000, 600));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Verdana", 2, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("Consultar Proyecto");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator1)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Seleccionar Proyecto");

        jcbProyecto.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbProyectoItemStateChanged(evt);
            }
        });

        jtTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Tareas", "Miembros", "Comentarios"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtTabla);
        if (jtTabla.getColumnModel().getColumnCount() > 0) {
            jtTabla.getColumnModel().getColumn(0).setResizable(false);
            jtTabla.getColumnModel().getColumn(1).setResizable(false);
            jtTabla.getColumnModel().getColumn(2).setResizable(false);
        }

        jcbEquipoMiembros.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbEquipoMiembrosItemStateChanged(evt);
            }
        });
        jcbEquipoMiembros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbEquipoMiembrosActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Seleccionar Miembro del Equipo");

        jbMostrar.setBackground(new java.awt.Color(0, 0, 0));
        jbMostrar.setForeground(new java.awt.Color(240, 240, 240));
        jbMostrar.setText("MOSTRAR TODAS LAS TAREAS DEL PROYECTO");
        jbMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMostrarActionPerformed(evt);
            }
        });

        jrbCompletada.setText("Completada");
        jrbCompletada.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jrbCompletada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbCompletadaActionPerformed(evt);
            }
        });

        jrbPendiente.setText("Pendiente");
        jrbPendiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbPendienteActionPerformed(evt);
            }
        });

        jrbProgreso.setText("En Progreso");
        jrbProgreso.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jrbProgreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbProgresoActionPerformed(evt);
            }
        });

        jbSalir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbSalir.setText("SALIR");
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));

        jbMostrarProyectos.setBackground(new java.awt.Color(0, 0, 0));
        jbMostrarProyectos.setForeground(new java.awt.Color(240, 240, 240));
        jbMostrarProyectos.setText("MOSTRAR TODOS LOS PROYECTOS");
        jbMostrarProyectos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMostrarProyectosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 721, Short.MAX_VALUE)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jbSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(309, 309, 309))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jcbEquipoMiembros, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jcbProyecto, 0, 474, Short.MAX_VALUE))
                                        .addGap(124, 124, 124))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jbMostrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jSeparator3)
                                            .addComponent(jbMostrarProyectos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(198, 198, 198))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jrbCompletada)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jrbProgreso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jrbPendiente))
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(196, 196, 196))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jcbProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbMostrar)
                .addGap(18, 18, 18)
                .addComponent(jbMostrarProyectos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jLabel3)
                .addGap(21, 21, 21)
                .addComponent(jcbEquipoMiembros, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbPendiente)
                    .addComponent(jrbProgreso)
                    .addComponent(jrbCompletada))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jrbCompletadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbCompletadaActionPerformed
        // TODO add your handling code here:
        armarModelo();
        if (jrbCompletada.isSelected()) {
            jrbCompletada.setSelected(true);
            jrbProgreso.setSelected(false);
            jrbPendiente.setSelected(false);
            Miembro miembro = ((EquipoMiembros) jcbEquipoMiembros.getSelectedItem()).getMiembro();
            tabla.setRowCount(0);
            for (Tarea t : datatarea.consultarTareasPorEquipoyMiembro(((EquipoMiembros) jcbEquipoMiembros.getSelectedItem()).getEquipo().getIdEquipo(), miembro.getIdMiembro())) {
                if (t.getEstado() == 0) {
                    tabla.addRow(new Object[]{t.getNombre(), t.getEquipomiembros().getMiembro(), t.getFechaCreacion(), t.getFechaCierre()});
                }
            }
        }
    }//GEN-LAST:event_jrbCompletadaActionPerformed

    private void jrbProgresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbProgresoActionPerformed
        // TODO add your handling code here:
        armarModelo();
        if (jrbProgreso.isSelected()) {
            jrbCompletada.setSelected(false);
            jrbProgreso.setSelected(true);
            jrbPendiente.setSelected(false);
            Miembro miembro = ((EquipoMiembros) jcbEquipoMiembros.getSelectedItem()).getMiembro();
            tabla.setRowCount(0);
            for (Tarea t : datatarea.consultarTareasPorEquipoyMiembro(((EquipoMiembros) jcbEquipoMiembros.getSelectedItem()).getEquipo().getIdEquipo(), miembro.getIdMiembro())) {
                if (t.getEstado() == 1) {
                    tabla.addRow(new Object[]{t.getNombre(), t.getEquipomiembros().getMiembro(), t.getFechaCreacion(), t.getFechaCierre()});
                }
            }
        }
    }//GEN-LAST:event_jrbProgresoActionPerformed

    private void jrbPendienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbPendienteActionPerformed
        // TODO add your handling code here:
        armarModelo();
        if (jrbPendiente.isSelected()) {
            jrbCompletada.setSelected(false);
            jrbProgreso.setSelected(false);
            jrbPendiente.setSelected(true);
            Miembro miembro = ((EquipoMiembros) jcbEquipoMiembros.getSelectedItem()).getMiembro();
            tabla.setRowCount(0);
            for (Tarea t : datatarea.consultarTareasPorEquipoyMiembro(((EquipoMiembros) jcbEquipoMiembros.getSelectedItem()).getEquipo().getIdEquipo(), miembro.getIdMiembro())) {
                if (t.getEstado() == 2) {
                    tabla.addRow(new Object[]{t.getNombre(), t.getEquipomiembros().getMiembro(), t.getFechaCreacion(), t.getFechaCierre()});
                }
            }
        }
    }//GEN-LAST:event_jrbPendienteActionPerformed

    private void jcbProyectoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbProyectoItemStateChanged
        // TODO add your handling code here:
        armarModelo();
        tabla.setRowCount(0);
        cargarMiembro();
    }//GEN-LAST:event_jcbProyectoItemStateChanged

    private void jcbEquipoMiembrosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbEquipoMiembrosItemStateChanged
        // TODO add your handling code here:
        Miembro miembro = ((EquipoMiembros) jcbEquipoMiembros.getSelectedItem()).getMiembro();
        armarModelo();
        tabla.setRowCount(0);
        for (Tarea t : datatarea.consultarTareasPorEquipoyMiembro(((EquipoMiembros) jcbEquipoMiembros.getSelectedItem()).getEquipo().getIdEquipo(), miembro.getIdMiembro())) {
            tabla.addRow(new Object[]{t.getNombre(), t.getEquipomiembros().getMiembro(), t.getFechaCreacion(), t.getFechaCierre()});

        }
    }//GEN-LAST:event_jcbEquipoMiembrosItemStateChanged

    private void jbMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMostrarActionPerformed
        armarModelo();
        tabla.setRowCount(0);
        Proyecto proyect = (Proyecto) jcbProyecto.getSelectedItem();
        for (Tarea t : datatarea.listarTareasPorProyecto(proyect.getIdProyecto())) {
            tabla.addRow(new Object[]{t.getNombre(), t.getEquipomiembros().getMiembro(), t.getFechaCreacion(), t.getFechaCierre()});
        }
    }//GEN-LAST:event_jbMostrarActionPerformed

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        dispose();
    }//GEN-LAST:event_jbSalirActionPerformed

    private void jbMostrarProyectosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMostrarProyectosActionPerformed
        // TODO add your handling code here:
        armarModelo2();
        tabla.setRowCount(0);
        for (Proyecto p : dataproyecto.consultarProyectos()) {
            tabla.addRow(new Object[]{p.getNombre(), dataequipomiembros.listarMiembrosPorProyecto(p.getIdProyecto()), p.getFechaInicio(), p.getDescripcion()});
        }
    }//GEN-LAST:event_jbMostrarProyectosActionPerformed

    private void jcbEquipoMiembrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbEquipoMiembrosActionPerformed
        // TODO add your handling code here:
        jrbCompletada.setSelected(false);
        jrbProgreso.setSelected(false);
        jrbPendiente.setSelected(false);
        Miembro miembro = ((EquipoMiembros) jcbEquipoMiembros.getSelectedItem()).getMiembro();
        armarModelo();
        tabla.setRowCount(0);
        for (Tarea t : datatarea.consultarTareasPorEquipoyMiembro(((EquipoMiembros) jcbEquipoMiembros.getSelectedItem()).getEquipo().getIdEquipo(), miembro.getIdMiembro())) {
            tabla.addRow(new Object[]{t.getNombre(), t.getEquipomiembros().getMiembro(), t.getFechaCreacion(), t.getFechaCierre()});

        }
    }//GEN-LAST:event_jcbEquipoMiembrosActionPerformed
    private void cargarProyecto() {
        DefaultComboBoxModel<Proyecto> cbox = new DefaultComboBoxModel();
        jcbProyecto.setModel(cbox);
        for (Proyecto proy : dataproyecto.consultarProyectos()) {
            jcbProyecto.addItem(proy);
        }
        if(jcbProyecto.getSelectedItem() == null){
            jbMostrar.setEnabled(false);
            jbMostrarProyectos.setEnabled(false);
            jcbEquipoMiembros.setEnabled(false);
            jrbProgreso.setEnabled(false);
            jrbPendiente.setEnabled(false);
            jrbCompletada.setEnabled(false);
        }
    }

    private void cargarMiembro() {
        DefaultComboBoxModel<EquipoMiembros> cbox = new DefaultComboBoxModel();
        jcbEquipoMiembros.setModel(cbox);
        for (EquipoMiembros equipmiemb : dataequipomiembros.listarEquipoMiembrosPorProyecto(((Proyecto) jcbProyecto.getSelectedItem()).getIdProyecto())) {
            jcbEquipoMiembros.addItem(equipmiemb);
        }
        if(jcbEquipoMiembros.getSelectedItem() == null){
            jrbProgreso.setEnabled(false);
            jrbPendiente.setEnabled(false);
            jrbCompletada.setEnabled(false);
        }
    }

    private void armarModelo() {
        tabla.setColumnCount(0);
        ArrayList titulos = new ArrayList();
        titulos.add("TAREAS");
        titulos.add("MIEMBROS");
        titulos.add("FECHA INICIO");
        titulos.add("FECHA CIERRE");
        for (Object titulo : titulos) {
            tabla.addColumn(titulo);
        }
        jtTabla.setModel(tabla);
    }

    private void armarModelo2() {
        tabla.setColumnCount(0);
        ArrayList titulos = new ArrayList();
        titulos.add("NOMBRE");
        titulos.add("MIEMBROS");
        titulos.add("FECHA INICIO");
        titulos.add("DESCRIPCION");
        for (Object titulo : titulos) {
            tabla.addColumn(titulo);
        }
        jtTabla.setModel(tabla);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JButton jbMostrar;
    private javax.swing.JButton jbMostrarProyectos;
    private javax.swing.JButton jbSalir;
    private javax.swing.JComboBox<EquipoMiembros> jcbEquipoMiembros;
    private javax.swing.JComboBox<Proyecto> jcbProyecto;
    private javax.swing.JRadioButton jrbCompletada;
    private javax.swing.JRadioButton jrbPendiente;
    private javax.swing.JRadioButton jrbProgreso;
    private javax.swing.JTable jtTabla;
    // End of variables declaration//GEN-END:variables
}
